import { Pool, type PoolClient } from 'pg';

import {
  DISPATCH_POINT_GEOGRAPHY_TYPE,
  DISPATCH_SPATIAL_INDEX_METHOD,
  DISPATCH_SPATIAL_SRID,
} from './spatial-conventions';

describe('dispatch spatial database conventions (integration)', () => {
  let pool: Pool;
  let client: PoolClient | undefined;
  let transactionStarted = false;

  beforeAll(async () => {
    pool = new Pool({ connectionString: process.env.DATABASE_URL });
    client = await pool.connect();
  });

  afterAll(async () => {
    client?.release();
    await pool.end();
  });

  beforeEach(async () => {
    if (!client) {
      return;
    }

    await client.query('BEGIN');
    transactionStarted = true;
  });

  afterEach(async () => {
    if (client && transactionStarted) {
      await client.query('ROLLBACK');
    }

    transactionStarted = false;
  });

  it('stores durable dispatch points as indexed SRID 4326 geography in lon/lat order', async () => {
    if (!client) {
      throw new Error('PostgreSQL client was not initialized');
    }

    await client.query(`
      CREATE TEMP TABLE dispatch_spatial_conventions_smoke (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pickup ${DISPATCH_POINT_GEOGRAPHY_TYPE} NOT NULL
      ) ON COMMIT DROP
    `);
    await client.query(`
      CREATE INDEX dispatch_spatial_conventions_smoke_pickup_idx
        ON dispatch_spatial_conventions_smoke
        USING ${DISPATCH_SPATIAL_INDEX_METHOD} (pickup)
    `);

    const columnResult = await client.query<{ columnType: string }>(`
      SELECT format_type(attribute.atttypid, attribute.atttypmod) AS "columnType"
      FROM pg_attribute attribute
      WHERE attribute.attrelid = 'dispatch_spatial_conventions_smoke'::regclass
        AND attribute.attname = 'pickup'
        AND NOT attribute.attisdropped
    `);

    expect(columnResult.rows[0]?.columnType).toBe(
      DISPATCH_POINT_GEOGRAPHY_TYPE,
    );

    await client.query(
      `
        INSERT INTO dispatch_spatial_conventions_smoke (pickup)
        VALUES (ST_SetSRID(ST_MakePoint($1, $2), $3)::geography)
      `,
      [38.7525, 9.0192, DISPATCH_SPATIAL_SRID],
    );

    const pointResult = await client.query<{
      srid: number;
      longitude: number;
      latitude: number;
      nearby: boolean;
      farAway: boolean;
    }>(
      `
        SELECT
          ST_SRID(pickup::geometry) AS srid,
          ST_X(pickup::geometry)::float8 AS longitude,
          ST_Y(pickup::geometry)::float8 AS latitude,
          ST_DWithin(
            pickup,
            ST_SetSRID(ST_MakePoint($1, $2), $3)::geography,
            2000
          ) AS "nearby",
          ST_DWithin(
            pickup,
            ST_SetSRID(ST_MakePoint($4, $5), $3)::geography,
            2000
          ) AS "farAway"
        FROM dispatch_spatial_conventions_smoke
      `,
      [38.7612, 9.0301, DISPATCH_SPATIAL_SRID, 36.8219, -1.2921],
    );

    expect(pointResult.rows[0]).toMatchObject({
      srid: DISPATCH_SPATIAL_SRID,
      longitude: 38.7525,
      latitude: 9.0192,
      nearby: true,
      farAway: false,
    });

    const indexResult = await client.query<{ indexMethod: string }>(`
      SELECT access_method.amname AS "indexMethod"
      FROM pg_class table_class
      INNER JOIN pg_index index_relation
        ON index_relation.indrelid = table_class.oid
      INNER JOIN pg_class index_class
        ON index_class.oid = index_relation.indexrelid
      INNER JOIN pg_am access_method
        ON access_method.oid = index_class.relam
      WHERE table_class.oid = 'dispatch_spatial_conventions_smoke'::regclass
        AND index_class.relname = 'dispatch_spatial_conventions_smoke_pickup_idx'
    `);

    expect(indexResult.rows[0]?.indexMethod).toBe(
      DISPATCH_SPATIAL_INDEX_METHOD,
    );
  });
});
